### ISSUE TITLE
How to generate “img_pair_list_dense.txt”？

### ISSUE THREAD

**Issue by colorblank** [dulucas/transformer-uvos#1]
Interesting idea and thanks for sharing the code. I was wandering how the each sample formed "reference image and current image". And would you like to share the "img_pair_list_dense.txt"? Really appreciate.

**Comment by dulucas** [comment]
```
path = '/path/to/DAVIS/JPEGImages/480p/'
import glob
 
train_list = open('/path/to/DAVIS/ImageSets/2017/train.txt', 'r').readlines()
w = open('img_pair_list_dense.txt', 'w')
 
for video in train_list:
    video = video.strip()
    imgs = glob.glob(path + video + '/*')
    imgs.sort()
    for i in range(len(imgs)):
        first_frame = imgs[i]
        for j in range(len(imgs)):
            if j == i:
                continue
            line = first_frame + '\t' + imgs[j] + '\n'
            w.write(line)
```

**Comment by colorblank** [comment]
Thanks. Have you think about use a random sampling strategy to obtian more pairs, may be more robust？

**Comment by dulucas** [comment]
The provided code exhaustively traverse all possible pairs of image. Sorry I don't understand what do you mean.

**Comment by colorblank** [comment]
> The provided code exhaustively traverse all possible pairs of image. Sorry I don't understand what do you mean.

For instance, your default setting is training with frame 1 and frame t. What I suggest is training with frame i and frame j.

**Comment by colorblank** [comment]
Never mind, I got a extremely low score:
![image](https://user-images.githubusercontent.com/16894837/110788510-af79a180-82a9-11eb-9a75-f3248981eb4a.png)

**Comment by dulucas** [comment]
The img_pair_list_dense.txt generated by the provided code contains all possible pairs of image. Please read the code.

**Comment by dulucas** [comment]
For the low score, please check your pre-trained model for initialization, I used [this](https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-PanopticSegmentation/panoptic_fpn_R_50_3x.yaml) model

**Comment by colorblank** [comment]
The weights are not from the "model_final_c10459.pkl"?

**Comment by dulucas** [comment]
The weights are from the "model_final_c10459.pkl", I changed its name to "res50_fpn_3x.pth" on my machine.

**Comment by colorblank** [comment]
Ok, thanks. I have change the code in "train.py" to load the weights you provided,like this:
```
    f = open(config.pretrained_model,'rb')
    pretrained_weights = pickle.load(f)['model']
    renamed_pretrained_weights = dict()
    for key in pretrained_weights:
        #if key == 'sem_seg_head.predictor.weight' or key == 'sem_seg_head.predictor.bias':
        #    continue
        if key[:14] == 'sem_seg_head.p':
            continue
        renamed_pretrained_weights['features.' + key] = torch.from_numpy(pretrained_weights[key])
        # print(key)
    names = model.load_state_dict(renamed_pretrained_weights, strict=False)
```
I think the pretrained weights are fine. Maybe the my sampling strategy went wrong.

FYI, the model [generating code]( https://github.com/dulucas/transformer-uvos/blob/dc554f3093ef0dd010ebb369faacc343662d6a50/model/transformer/davis.transformer.fpn.R50.random_sample/eval.py#L116) in  "eval.py" has some issues. And I changed to this:
```
        cfg = get_cfg()
        cfg.merge_from_file('./fpn_config/semantic_R_50_FPN_1x.yaml')
        model = AnchorDiffNet(cfg, embedding=cfg.MODEL.SEM_SEG_HEAD.CONVS_DIM, batch_mode='sync')
```

Besides, the [upsampling ](https://github.com/dulucas/transformer-uvos/blob/dc554f3093ef0dd010ebb369faacc343662d6a50/model/transformer/davis.transformer.fpn.R50.random_sample/semantic_seg.py#L59)in "FPN" also went wrong, you may change to this style :`F.interpolate(x, size=x.shape[-2:], mode='bilinear', align_corners=True)`.

**Comment by dulucas** [comment]
Thanks, indeed, the eval.py is not the correct version. For the upsampling, I didn't encounter any problems. I guess maybe it's because your input size can not divisible by 32.

**Comment by colorblank** [comment]
I use the setting you provided to reshape images to (857, 481). So, yes.

**Comment by dulucas** [comment]
Isn't it 640x352?

**Comment by colorblank** [comment]
It is  (857, 481) in this [line](https://github.com/dulucas/transformer-uvos/blob/dc554f3093ef0dd010ebb369faacc343662d6a50/model/transformer/davis.transformer.fpn.R50.random_sample/eval.py#L141) . It's the evaluation setting. The training is fine.

**Comment by dulucas** [comment]
OK, the eval.py is not the correct version. I will change it later. Thanks

**Comment by colorblank** [comment]
Would you mind telling me how long you spend on training and what's your GPU?

**Comment by dulucas** [comment]
GPU: 4x2080 Ti
Training Time: about 6hours? But the results should be close to the final results from epoch-10.

**Comment by colorblank** [comment]
Thanks a lot.
